// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'profile.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'profile.g.dart';

@freezed
class Profile with _$Profile {
  //i putted all the fields dynamic because there is not API doc that till what they should be
  const factory Profile({
    required dynamic customer_id,
    required dynamic name,
    required dynamic phone,
    required dynamic email,
    required dynamic eng_name,
    required dynamic username,
    required DateTime join_date,
    required dynamic wallet_balance,
    required dynamic cash_back_coupon,
    required dynamic statistics,
  }) = _Profile;

  //TODO statistics adding
  factory Profile.fromJson(Map<String, Object?> json) =>
      _$ProfileFromJson(json);
}
